import type { Metadata } from "next";
import "./globals.css";
import Sidebar from '@/components/Sidebar'
import Navbar from '@/components/Navbar'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Sidebar />
          <div className="flex-1 min-h-screen bg-[#E8EAF3]">
            <Navbar />
            {children}
          </div>
        </div>
        
      </body>
    </html>
  );
}
